version: '2'
services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    external_links:
      - digest_mongo_1:mongo
    networks:
      - digest_default

networks:
  digest_default:
    external: true
